"""add_question_batch_models

Revision ID: 3aefb75602a4
Revises: 3df5f9c6de27
Create Date: 2026-08-08 02:15:52.511499

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3aefb75602a4"
down_revision: Union[str, Sequence[str], None] = "3df5f9c6de27"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "questions_batch",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("topic", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "questions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("question", sa.String(), nullable=True),
        sa.Column("batch_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["questions_batch.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("questions")
    op.drop_table("questions_batch")
    # ### end Alembic commands ###
